# Generated by Django 6.0.6 on 2026-07-04 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('Abordando', 'Abordando'), ('En vuelo', 'En vuelo'), ('Aterrizado', 'Aterrizado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=15)),
                ('asientos', models.IntegerField(help_text='Asientos totales o disponibles')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajero_nombre', models.CharField(max_length=150)),
                ('pasajero_cedula', models.CharField(max_length=10)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Pago'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=15)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vuelos.vuelo')),
            ],
        ),
    ]
