# Generated by Django 6.0.6 on 2026-07-05 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pasajero_cedula',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe tener exactamente 10 números.')]),
        ),
    ]
