# Generated by Django 6.0.5 on 2026-07-05 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_alter_reserva_pasajero_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Pago'), ('Confirmada', 'Confirmada')], default='Pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero_cedula',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe tener exactamente números (10).')]),
        ),
    ]
