# Generated by Django 6.0.5 on 2026-07-06 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0003_alter_reserva_estado_alter_reserva_pasajero_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pasajero_cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente números (10).', regex='^\\d{10}$')]),
        ),
    ]
